src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Person::class, inversedBy="news")
     */
    private $person;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(?Person $person): self
    {
        $this->person = $person;

        return $this;
    }
}

src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\News;
use App\Repository\PersonRepository;
use App\FormSubscriber\NewsTypeSubscriber;
use Symfony\Component\Form\AbstractType;
use Kematjaya\HiddenTypeBundle\Type\HiddenDateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormError;

class NewsType extends AbstractType
{
    private $repo;
    
    public function __construct(PersonRepository $repo) 
    {
        $this->repo = $repo;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('created_at', HiddenDateTimeType::class)
            ->add('title')
            ->add('content', ChoiceType::class, [
                'choices' => array_flip($this->repo->getPersonArray())
            ])
            ->add('person', EntityType::class, [
                'class' => \App\Entity\Person::class
            ])
        ;
        
        //// CARA 1
        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event){
            $event->getForm()
                    ->add('title', \Symfony\Component\Form\Extension\Core\Type\TextareaType::class, [
                        'attr' => ['onchange' => 'alert("aa")']
                    ]);
        });
        
        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
            $data = $event->getData();
            if (strlen($data->getTitle()) > 4) {
                $event
                        ->getForm()
                        ->get('title')
                        ->addError(new FormError("judul tidak boleh lebih dari 4 karakter"));
            }
        });
        
        // CARA 2
        $builder->addEventSubscriber(new NewsTypeSubscriber());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

src/Controller/Admin/NewsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\News;
use App\Form\NewsType;
use App\Repository\NewsRepository;
use App\Filter\NewsFilterType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Kematjaya\BaseControllerBundle\Controller\BaseLexikFilterController as BaseController;

/**
 * @Route("/news", name="news_")
 */
class NewsController extends BaseController
{
    /**
     * @Route("/", name="index", methods={"GET", "POST"})
     */
    public function index(Request $request, NewsRepository $newsRepository): Response
    {
        $form = $this->createFormFilter(NewsFilterType::class);
        $queryBuilder = $this->buildFilter($request, $form, $newsRepository->createQueryBuilder('this'));
                
        return $this->render('news/index.html.twig', [
            'news' => parent::createPaginator($queryBuilder, $request), 
            'filter' => $form->createView() 
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $news = new News();
        $form = $this->createForm(NewsType::class, $news, [
            'attr' => ['id' => 'ajaxForm', 'action' => $this->generateUrl('news_new')]
        ]);
        $result = parent::processFormAjax($request, $form);
        if ($result['process']) {
            return $this->json($result);
        }

        return $this->render('news/form.html.twig', [
            'news' => $news,
            'form' => $form->createView(), 'title' => 'new'
        ]);
    }

    /**
     * @Route("/{id}/show", name="show", methods={"GET"})
     */
    public function show(News $news): Response
    {
        return $this->render('news/show.html.twig', [
            'news' => $news,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, News $news): Response
    {
        $form = $this->createForm(NewsType::class, $news, [
            'attr' => ['id' => 'ajaxForm', 'action' => $this->generateUrl('news_edit', ['id' => $news->getId()])]
        ]);
        
        $result = parent::processFormAjax($request, $form);
        if ($result['process']) {
            return $this->json($result);
        }

        return $this->render('news/form.html.twig', [
            'news' => $news,
            'form' => $form->createView(), 'title' => 'edit'
        ]);
    }

    /**
     * @Route("/{id}/delete", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, News $news): Response
    {
        $tokenName = 'delete'.$news->getId();
        parent::doDelete($request, $news, $tokenName);
        
        return $this->redirectToRoute('news_index');
    }
}

templates/news/_delete_form.html.twig
<form method="post" action="{{ path('news_delete', {'id': news.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
    <button class="btn btn-xs btn-danger"><span class="fa fa-trash"></span> {{ 'delete'|trans }}</button>
</form>

templates/news/_filters.html.twig
{{ form_start(filter) }}
<tr>
    <td>{{ form_widget(filter.created_at) }}</td>
    <td>{{ form_widget(filter.title) }}</td>
    <td>{{ form_widget(filter.content) }}</td>
    <td>{{ form_widget(filter.person) }}</td>
    <td>
    <button type="submit" name="submit" class="btn btn-success btn-sm"><i class="fa fa-search"></i> <span>{{ 'filter'|trans }}</span></button>
        <a href="{{path('news_index', {'_reset' : true })}}" class="btn btn-default btn-sm"><i class="fa fa-recycle"></i> <span>{{ 'reset'|trans }}</span></a>
    </td>
</tr>
{{ form_end(filter) }}

templates/news/_max_per_page.html.twig
<form method="GET" action="{{path(url)}}">
    <select class="form-control show-tick" name="_limit" onchange="this.form.submit()">
        <option>{{ 'max_per_page'|trans }}</option>
        {% for v in [5, 10, 20, 50, 100] %}
            {% if v == app.request.session.get('limit')%}
                <option value="{{v}}" selected>{{v}}</option>
            {% else %}
                <option value="{{v}}">{{v}}</option>
            {% endif %}
        {% endfor %}
    </select>
</form>

templates/news/form.html.twig
{% extends '@BaseController/modal-layout.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block content %}
    
    {{ form_widget(form) }}
        
{% endblock %} 

{% block form_start %}
    
    {{ form_start(form) }}
    
{% endblock %}

{% block form_end %}
    
    {{ form_end(form) }}
    
{% endblock %}

{% block actions %}
    <button class="btn btn-sm btn-success">
        <span class="fa fa-save"></span> 
        {{ 'save'|trans }}
    </button>
{% endblock %}
    

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}news{% endblock %}

{% block content %}
    <h1>{{ 'news'|trans }}</h1>
    <div class="pull-right">
        <a class="btn btn-sm btn-success" href="{{ path('news_new') }}" data-toggle="modal" data-target="#myModal">
            <span class="fa fa-plus"></span> {{ 'create'|trans }}</a>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>               
                    <th>{{ 'created_at'|trans }}</th>
                    <th>{{ 'title'|trans }}</th>
                    <th>{{ 'content'|trans }}</th>
                    <th>{{ 'person'|trans }}</th>
                    <th>{{ 'actions'|trans }}</th>
                </tr>
            </thead>
            <tbody>

                {{ include('news/_filters.html.twig', {filter: filter}) }} 
                {% for news in news %}
                <tr>                                                                                
                    <td>{{ news.createdAt ? news.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ news.title }}</td>
                    <td>{{ news.content }}</td>
                    <td>{{ news.person }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ path('news_show', {'id': news.id}) }}" data-toggle="modal" data-target="#myModal"><span class="fa fa-desktop"></span> {{ 'show'|trans }}</a>
                        <a class="btn btn-xs btn-info" href="{{ path('news_edit', {'id': news.id}) }}" data-toggle="modal" data-target="#myModal"><span class="fa fa-edit"></span> {{ 'edit'|trans }}</a>
                        {{ include('news/_delete_form.html.twig', {news: news}) }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">{{ 'no_records_found'|trans }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-lg-2">
        {{ include('news/_max_per_page.html.twig', {url: 'news_index'}) }}
    </div>
    <div class="pull-right">
        <style>
            .pagination {
                margin : 0px;
            }
        </style>
        <div class="pagerfanta pull-right">
            {{ knp_pagination_render(news) }}
        </div>
    </div>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block content %}

    <h1>{{ 'show'|trans}} News</h1>

    <table class="table table-bordered table-hover">
        <tbody>
                        <tr>
                <th>Id</th>
                <td>{{ news.id }}</td>
            </tr>
                        <tr>
                <th>Created_at</th>
                <td>{{ news.createdAt ? news.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
                        <tr>
                <th>Title</th>
                <td>{{ news.title }}</td>
            </tr>
                        <tr>
                <th>Content</th>
                <td>{{ news.content }}</td>
            </tr>
                    </tbody>
    </table>

    <a class="btn btn-sm btn-primary" href="{{ path('news_index') }}" ><span class="fa fa-list"></span> {{ 'back'|trans }}</a>

    <a class="btn btn-sm btn-info" href="{{ path('news_edit', {'id': news.id}) }}"><span class="fa fa-edit"></span> {{ 'edit'|trans }}</a>

{% endblock %}